package com.infernalsuite.iwm.api.event.events.world;

import com.infernalsuite.iwm.api.event.IWMEvent;
import com.infernalsuite.iwm.api.event.util.Param;
import com.infernalsuite.iwm.api.world.InfernalWorld;
import org.checkerframework.checker.nullness.qual.NonNull;

/**
 * Called once world generation has been completed.
 *
 * <p>Contains the name and {@link InfernalWorld world} which has been generated by IWM.</p>
 */
public interface PostGenerateWorldEvent extends IWMEvent {

    /**
     * Gets the name of the world which has been generated.
     *
     * @return the world name
     */
    @Param(0)
    @NonNull String getWorldName();

    /**
     * Gets the {@link InfernalWorld world} which has been generated.
     *
     * @return the world
     */
    @Param(1)
    @NonNull InfernalWorld getWorld();

}
